sessions_controller
LeoXman/monsters pull request #11
Opened 2017-03-12 10:33 UTC by LeoXman

Optimisation of all controllers

2017-03-12 10:56 UTC, riley-usagi approved these changes

2017-03-12 10:56 UTC, riley-usagi commented on app/controllers/sessions_controller.rb
> +        username: params[:sessions][:username],
Не густо, но хоть работает =)

Хотя стоило бы в отдельный коммит пихать хотя бы полное исправление файла, а не по одному исправлению на коммит.

2017-03-12 12:52 UTC, riley-usagi requested changes

2017-03-12 12:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +    @letter = Monster.letterize(params[:letter])
Необходимо выравнивание по знаку **=**

Везде по проекту.

2017-03-12 12:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +                  flash: {
Не правильное выравнивание. Это можно в одну строку написать.

2017-03-12 12:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +                      notice: 'Monster was successfully created.'
В который раз повторяю - определись с языком. Или русский или английский.

2017-03-12 12:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +                  flash: {
Можно в одну строчку.

2017-03-12 12:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +                  flash: {
Тоже самое. В одну строку.

2017-03-12 12:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  def check_own?(id)
Какой смысл несёт название этого метода?
По названию должно бытьп онятно, что делает этот метод.

2017-03-12 12:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +    user = current_user.id
Выравнивание по символу **=**

2017-03-12 12:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
>      params.require(:monster).permit(
Всё это пишется в одну кучу, с переносом в районе 80-го символа. Уже обсуждали это вчера.

2017-03-12 12:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
>      params.require(:monster).permit(
Можно в одну строчку написать вообще.

2017-03-12 12:54 UTC, riley-usagi requested changes

2017-03-12 12:54 UTC, riley-usagi commented on app/controllers/messages_controller.rb
> +# Сообщения пользователей
Сообщения куда?

2017-03-12 12:54 UTC, riley-usagi commented on app/controllers/messages_controller.rb
>      @user = User.find(params[:user_id])
Выравнивание по смиволу **=**

2017-03-12 12:54 UTC, riley-usagi approved these changes

2017-03-12 17:59 UTC, riley-usagi approved these changes

2017-03-12 17:59 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +                      notice: 'Монстер создан.'
Нет такого слова - *'монстер'* =)

2017-03-13 08:37 UTC, riley-usagi requested changes

2017-03-13 08:37 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
>      @monster = Monster.find(monster)
Ты берёшь объект модели **Monster**, от него берёшь его **id**, передаёшь этот **id** в приватный метод и в этом приватном методе по этому **id** опять ищешь этот самый объект модели **Monster**.

Я в шоке.

Почему бы сразу не передать в приватный метод сам объект модели **Monster**?

Перечитай про ООП.

2017-03-13 11:16 UTC, riley-usagi requested changes
Куча базовых ошибок.

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  # Форма создание нового монстра
созданиЯ

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
>    def create
Этого метода у тебя вообще не должно быть в проекте.
По двум причинам:

1. В базе уже есть все монстры.
2. Если ты вдруг и захотел что-либо добавлять, то добавляй через **ActiveAdmin**, раз уж собрался его использовать. 

Убери этот метод.

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  # Обновление монстра
Тоже самое что с методом **create**

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  def check_own?(id)
Необходимо нормальное название для метода, чтобы сразу было понятно что он делает.

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  # Обновления счетчика избранных монстров
По комментарию всё ещё не понятно что делает этот метод.
По коду, собственно, тоже не понятно что он делает.

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +                                    :vit, :int, :dex, :luk, :scale, :own)
**own** переводится как - *своя*.
И что значит эта - *своя*?

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  def monster_params
Даже само название метода обозначает работу с параметрами модели **Monster**.
В твоей модели нет поля - **own**. Соответственно и здесь его быть не должно, если ты при создании/обновлении объекта используешь метод ```monster_params```, то в него попадает и таинственный **own**, который создаёт ошибку фактом собственного отсутствия. 

Подобные методы это реализация функционала **Strong Parameters** в Rails 4+ и ты обязан знать что это, зачем используется, а главное - как.

В данном случае если у тебя из форм на сайте приходят какие-либо данные в данный контролёр, то они должны быть разделены на разные методы. Не нужно их все мешать в один метод ```_params```

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  def comment_params
Вот здесь сделано правильно. Только синтаксис хромает.

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
>      params.require(:monster).permit(
Почему вся эта борода у тебя занимает аж три строчки?!

2017-03-13 11:16 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  end
Не используй в проекте зарезервированные слова вроде **text**. 
Здесь вполне подойдёт и **content**

2017-03-13 11:16 UTC, riley-usagi commented on app/models/ability.rb
> +      can :dislike, Monster do |monster|
Лайки и дислайки удаляй из проекта.

2017-03-13 11:19 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  def check_own?(id)
Не понимаю почему ты не пользуешься переводчиком. Из принципа?

Переводчик от гугла вполне сносно справляется с подобным и выдаёт вариант: **Owner verification**

2017-03-13 11:52 UTC, riley-usagi requested changes

2017-03-13 11:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +  def check_monster_owner?(id)
Не идеально, но уже намного лучше.

2017-03-13 11:52 UTC, riley-usagi commented on app/controllers/monsters_controller.rb
> +    params.require(:monster).permit(:сщт)
Шта?)

2017-03-13 12:01 UTC, riley-usagi requested changes
Необходимы исправления.

2017-03-13 12:01 UTC, riley-usagi commented on app/assets/javascripts/poll.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
Тебе в самых базовых настройках приложения нужно удалить из генератора создание ненужных файлов.

2017-03-13 12:01 UTC, riley-usagi commented on app/controllers/poll_controller.rb
> +class PollController < ApplicationController
Пустой класс. Если он нужен тебе на будущее, то описывай его правильно.

Ты в очередной раз залил код не проверив его рубокопом.

2017-03-13 12:01 UTC, riley-usagi commented on app/controllers/vote_controller.rb
> +class VoteController < ApplicationController
Тоже самое - неправильный код.

2017-03-13 12:01 UTC, riley-usagi commented on app/helpers/poll_helper.rb
> +module PollHelper
Пустой файл. Не нужен.

2017-03-13 12:01 UTC, riley-usagi commented on app/helpers/vote_helper.rb
> +module VoteHelper
Пустой файл. Не нужен.

2017-03-13 12:01 UTC, riley-usagi commented on app/models/poll.rb
> +class Poll < ActiveRecord::Base
Код неправильный.

2017-03-13 12:01 UTC, riley-usagi commented on app/models/vote.rb
> +class Vote < ActiveRecord::Base
Код неправильный.

2017-03-13 12:01 UTC, riley-usagi commented on spec/controllers/poll_controller_spec.rb
> +
Должен быть ```pending```

2017-03-13 12:01 UTC, riley-usagi commented on db/migrate/20170313115007_create_votes.rb
> +
Пустая миграция. В таблице должны быть поля.

2017-03-13 12:01 UTC, riley-usagi commented on spec/controllers/vote_controller_spec.rb
> +
```pending```

2017-03-13 12:01 UTC, riley-usagi commented on app/controllers/poll_controller.rb
> +class PollController < ApplicationController
```ruby
class PollController < ApplicationController; end;
```

2017-03-13 13:35 UTC, riley-usagi requested changes
Ошибки

2017-03-13 13:35 UTC, riley-usagi commented on app/controllers/poll_controller.rb
> +  PollController < ApplicationController
Что это?!
Я же тебе скидывал готовый рабочий вариант кода. А это просто ошибка и ничего более. 

Как можно вместо копирования готового рабочего кода сделать только хуже и считать это правильным решением? =(

2017-03-13 13:35 UTC, riley-usagi commented on app/controllers/vote_controller.rb
> +  VoteController < ApplicationController
Косяк

2017-03-13 13:35 UTC, riley-usagi commented on config/application.rb
> +      g.stylesheets     false
Делается всё в одну строку. Пример я тебе кидал в телеграме.

2017-03-13 13:35 UTC, riley-usagi commented on spec/controllers/poll_controller_spec.rb
> -require 'rails_helper'
Писал уже сегодня. И не раз. Нужны ```pending``` в пустых тестах. А ты все тесты удалил к хренам...

2017-03-13 15:00 UTC, LeoXman commented on spec/controllers/poll_controller_spec.rb
> -require 'rails_helper'
Что это?

2017-03-13 15:03 UTC, riley-usagi commented on spec/controllers/poll_controller_spec.rb
> -require 'rails_helper'
Приплыли.

Не ты ли мне доказывал что разобрался с тестами?

```pending``` это то, с чего начинается любой тест и с чего начинается обучение тестам. Это самые азы азов.

2017-03-13 15:04 UTC, riley-usagi commented on spec/controllers/poll_controller_spec.rb
> -require 'rails_helper'
Более того - ты мог бы просто запустить тест с ним и без него и понять что это.

2017-03-13 15:04 UTC, riley-usagi commented on spec/controllers/poll_controller_spec.rb
> -require 'rails_helper'
Не так уж и сложно написать одно слово.

2017-03-13 15:06 UTC, riley-usagi requested changes

2017-03-13 15:06 UTC, riley-usagi commented on app/controllers/vote_controller.rb
> +class VoteController < ApplicationController
Всё ещё неправильный код.

2017-03-13 15:06 UTC, riley-usagi commented on app/controllers/poll_controller.rb
> +class PollController < ApplicationController
Написал готовый вариант.
Всё ещё не исправлено. Добей его уже.

2017-03-13 15:46 UTC, riley-usagi requested changes

2017-03-13 15:46 UTC, riley-usagi commented on app/controllers/poll_controller.rb
>  class PollController < ApplicationController
Неправильный код.

Правильный вариант я уже писал в ревью ранее.

2017-03-13 15:46 UTC, riley-usagi commented on app/controllers/vote_controller.rb
>  class VoteController < ApplicationController
Неправильный код.

Правильный вариант я уже писал в ревью ранее.

2017-03-13 17:27 UTC, riley-usagi approved these changes
Куча не критичных мелочей. 

Но раз уж взялись всерьёз, то стоит поправить перед слиянием.

2017-03-13 17:27 UTC, riley-usagi commented on app/controllers/sessions_controller.rb
> +      session[:user_id] = user.id redirect_to root_path
Здесь не нужно было в одну строку.

2017-03-13 17:27 UTC, riley-usagi commented on app/controllers/sessions_controller.rb
> +    redirect_to root_path, flash: { success: 'Вы успешно вышли из аккаунта.' }
Невозможно выйти из аккаунта.  Из системы, да. С сайта. Аккаунт можно только удалить.

2017-03-13 17:27 UTC, riley-usagi commented on app/controllers/users_controller.rb
> -  # GET /users
Просто взял и удалил список пользователей? Я предлагал удалить создание, обновление и удаление и перенести их потом в админку.

2017-03-13 17:27 UTC, riley-usagi commented on app/controllers/users_controller.rb
> +  # Обновление пользователей
Профиль в единственном лице, а создание почему-то во множественном. Вообще-то ты создаёшь в методе один объект, а не несколько.

2017-03-13 17:27 UTC, riley-usagi commented on app/controllers/users_controller.rb
> +                    notice: 'Данные пользователя обновлены.'
Данные обновлены. 
Разве так не проще? Меньше места занимает и унифицировано.

2017-03-13 17:27 UTC, riley-usagi commented on app/controllers/users_controller.rb
> +  # Удаление пользователей
Тоже самое.

2017-03-13 17:27 UTC, riley-usagi commented on app/controllers/vote_controller.rb
> +class VoteController < ApplicationController
Голоса, голоса повсюду мне слышны. 
Призраков голоса.

2017-03-13 17:27 UTC, riley-usagi commented on app/models/monster.rb
> +  has_one :poll
Has_one уже давно не используется в рельсах. Можно опустить эту строчку.

2017-03-13 17:27 UTC, riley-usagi commented on app/models/monster.rb
> +    where('UPPER(name) LIKE UPPER(?)', "#{letter}%")
Вдеться это можно написать и через обычный AR. С телефона не могу проверить.

2017-03-13 17:27 UTC, riley-usagi commented on db/migrate/20170313130929_create_polls.rb
> +      t.timestamps null: false
Обычно ставят пустую строку в миграциях перед таймстампами.

2017-03-13 17:27 UTC, riley-usagi commented on db/migrate/20170313130948_create_votes.rb
> +      t.timestamps null: false
Тоже самое. Пропуск.

2017-03-13 17:45 UTC, merged